name: Auto Update Programmers Badges

on:
  schedule:
    # 매일 오전 9시에 실행
    - cron: '0 9 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Auto Update Programmers Badges
      run: |
        python auto_update_badges.py
      env:
        PROGRAMMERS_USERNAME: ${{ secrets.PROGRAMMERS_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto update programmers badges [skip ci]"
        git push 