name: Update Programmers Stats

on:
  schedule:
    # 매일 오전 9시에 실행
    - cron: '0 9 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update Programmers Badges
      run: |
        python programmers_badge_generator.py
      env:
        PROGRAMMERS_USERNAME: ${{ secrets.PROGRAMMERS_USERNAME }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md programmers_stats.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update programmers badges [skip ci]"
        git push 